project_id = "vshtdxfcgdaorghaozjl"

[functions.chat]
verify_jwt = false

[functions.import-notes]
verify_jwt = false

[functions.google-calendar-auth]
verify_jwt = false

[functions.google-calendar-api]
verify_jwt = false

[functions.store-api-key]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.shared-note]
verify_jwt = false

[functions.note-ai-chat]
verify_jwt = false

[functions.improve-text]
verify_jwt = false

[functions.parse-voice-task]
verify_jwt = false

[functions.transcribe-meeting-audio]
verify_jwt = false

[functions.telegram-poll]
verify_jwt = false

[functions.telegram-send]
verify_jwt = false
