project_id = "vshtdxfcgdaorghaozjl"

[functions.chat]
verify_jwt = false

[functions.import-notes]
verify_jwt = false

[functions.google-calendar-auth]
verify_jwt = false

[functions.google-calendar-api]
verify_jwt = false

[functions.store-api-key]
verify_jwt = false
